### ISSUE TITLE
4 People in the Room

### ISSUE THREAD

**Issue by sonnynomnom** [ajayrwarrier/Video-Chat#2]
Hi @ajayrwarrier, 

I just finished your class (loved it) and I am currently trying to use WebRTC for my side project, [Karaoke Nite](https://karaokenite.co) v0.2.

Can you make a branch on how to allow up to 4 people in the video chat room, instead of 2?

Happy to jump on a Zoom call, too, if that's faster. My email is sonny@codecademy.com.

**Comment by ajayrwarrier** [comment]
Hey, we'll need a media server for that. Unfortunately, there are no good media servers with proper documentation. Twilio and Agora are two good options.

If you want an open-source one, try media soup. But the documentation is not that great.
https://github.com/versatica/mediasoup

**Comment by sonnynomnom** [comment]
Oh, bummer. What about three people in the room?

Also, is Vonage any good?

**Comment by ajayrwarrier** [comment]
Never heard of Vonage before. If you can make sense of the documentation then go ahead.
You can make it three people in the room by adding one more rtcpeerconnection variable and hardcoding the connections just like when we had two peers. You'll also need to change the UI to show three streams instead of 2. You can also do this for 4 people but the bandwidth requirement will be very high for stable conversations/.
